def makeFlags(sheet):
    """Appends new flags to the GlobalFlags datasheet to use for the Heart Pieces, Instruments, and Trade Items"""
    
    sheet['values'].append({'symbol': 'AnimalVillageHeartGet', 'index': 1119})
    sheet['values'].append({'symbol': 'AnimalVillageCaveHeartGet', 'index': 1120})
    sheet['values'].append({'symbol': 'TaltalEntranceBlocksHeartGet', 'index': 1121})
    sheet['values'].append({'symbol': 'NorthWastelandHeartGet', 'index': 1122})
    sheet['values'].append({'symbol': 'DesertCaveHeartGet', 'index': 1123})
    sheet['values'].append({'symbol': 'GraveyardCaveHeartGet', 'index': 1124})
    sheet['values'].append({'symbol': 'MabeWellHeartGet', 'index': 1125})
    sheet['values'].append({'symbol': 'UkukuCaveWestHeartGet', 'index': 1126})
    sheet['values'].append({'symbol': 'UkukuCaveEastHeartGet', 'index': 1127})
    sheet['values'].append({'symbol': 'BayPassageHeartGet', 'index': 1128})
    sheet['values'].append({'symbol': 'RiverCrossingHeartGet', 'index': 1129})
    sheet['values'].append({'symbol': 'RapidsWestHeartGet', 'index': 1130})
    sheet['values'].append({'symbol': 'RapidsAscentHeartGet', 'index': 1131})
    sheet['values'].append({'symbol': 'KanaletMoatHeartGet', 'index': 1132})
    sheet['values'].append({'symbol': 'SouthBayHeartGet', 'index': 1133})
    sheet['values'].append({'symbol': 'TaltalCrossingHeartGet', 'index': 1134})
    sheet['values'].append({'symbol': 'TaltalEastHeartGet', 'index': 1135})
    sheet['values'].append({'symbol': 'TaltalWestHeartGet', 'index': 1136})
    sheet['values'].append({'symbol': 'TurtleRockHeartGet', 'index': 1137})
    sheet['values'].append({'symbol': 'PotholeHeartGet', 'index': 1138})
    sheet['values'].append({'symbol': 'WoodsCrossingHeartGet', 'index': 1139})
    sheet['values'].append({'symbol': 'WoodsNorthCaveHeartGet', 'index': 1140})
    sheet['values'].append({'symbol': 'DiamondIslandHeartGet', 'index': 1141})

    sheet['values'].append({'symbol': 'TailCaveInstrumentGet', 'index': 1142})
    sheet['values'].append({'symbol': 'BottleGrottoInstrumentGet', 'index': 1143})
    sheet['values'].append({'symbol': 'KeyCavernInstrumentGet', 'index': 1144})
    sheet['values'].append({'symbol': 'AnglersTunnelInstrumentGet', 'index': 1145})
    sheet['values'].append({'symbol': 'CatfishsMawInstrumentGet', 'index': 1146})
    sheet['values'].append({'symbol': 'FaceShrineInstrumentGet', 'index': 1147})
    sheet['values'].append({'symbol': 'EaglesTowerInstrumentGet', 'index': 1148})
    sheet['values'].append({'symbol': 'TurtleRockInstrumentGet', 'index': 1149})
    
    sheet['values'].append({'symbol': 'TradeYoshiDollGet', 'index': 1150})
    sheet['values'].append({'symbol': 'TradeRibbonGet', 'index': 1151})
    sheet['values'].append({'symbol': 'TradeDogFoodGet', 'index': 1152})
    sheet['values'].append({'symbol': 'TradeBananasGet', 'index': 1153})
    sheet['values'].append({'symbol': 'TradeStickGet', 'index': 1154})
    sheet['values'].append({'symbol': 'TradeHoneycombGet', 'index': 1155})
    sheet['values'].append({'symbol': 'TradePineappleGet', 'index': 1156})
    sheet['values'].append({'symbol': 'TradeHibiscusGet', 'index': 1157})
    sheet['values'].append({'symbol': 'TradeLetterGet', 'index': 1158})
    sheet['values'].append({'symbol': 'TradeBroomGet', 'index': 1159})
    sheet['values'].append({'symbol': 'TradeFishingHookGet', 'index': 1160})
    sheet['values'].append({'symbol': 'TradeNecklaceGet', 'index': 1161})
    sheet['values'].append({'symbol': 'TradeMermaidsScaleGet', 'index': 1162})
    sheet['values'].append({'symbol': 'TradeLensGet', 'index': 1163})

    sheet['values'].append({'symbol': 'KikiGone', 'index': 1164})

    sheet['values'].append({'symbol': 'BombsFound', 'index': 1165})
    sheet['values'].append({'symbol': 'BombBagFound', 'index': 1166})

    sheet['values'].append({'symbol': 'MushroomFound', 'index': 1167})
    sheet['values'].append({'symbol': 'PowderBagFound', 'index': 1168})

    sheet['values'].append({'symbol': 'PotholeGet', 'index': 1169})

    sheet['values'].append({'symbol': 'ShopShovelGet', 'index': 1170})
    sheet['values'].append({'symbol': 'ShopBowGet', 'index': 1171})
    # sheet['values'].append({'symbol': 'ShopShovelGet', 'index': 1170})
    # sheet['values'].append({'symbol': 'ShopShovelGet', 'index': 1170})
    # sheet['values'].append({'symbol': 'ShopShovelGet', 'index': 1170})
    # sheet['values'].append({'symbol': 'ShopShovelGet', 'index': 1170})
    # sheet['values'].append({'symbol': 'ShopShovelGet', 'index': 1170})
    # sheet['values'].append({'symbol': 'ShopShovelGet', 'index': 1170})