def makeFlags(sheet):
    """Appends new flags to the GlobalFlags datasheet to use for Heart Pieces, Instruments, Trade Items, and Companions"""
    
    sheet['values'].append({'symbol': 'AnimalVillageHeartGet', 'index': 1119})
    sheet['values'].append({'symbol': 'AnimalVillageCaveHeartGet', 'index': 1120})
    sheet['values'].append({'symbol': 'TaltalEntranceBlocksHeartGet', 'index': 1121})
    sheet['values'].append({'symbol': 'NorthWastelandHeartGet', 'index': 1122})
    sheet['values'].append({'symbol': 'DesertCaveHeartGet', 'index': 1123})
    sheet['values'].append({'symbol': 'GraveyardCaveHeartGet', 'index': 1124})
    sheet['values'].append({'symbol': 'MabeWellHeartGet', 'index': 1125})
    sheet['values'].append({'symbol': 'UkukuCaveWestHeartGet', 'index': 1126})
    sheet['values'].append({'symbol': 'UkukuCaveEastHeartGet', 'index': 1127})
    sheet['values'].append({'symbol': 'BayPassageHeartGet', 'index': 1128})
    sheet['values'].append({'symbol': 'RiverCrossingHeartGet', 'index': 1129})
    sheet['values'].append({'symbol': 'RapidsWestHeartGet', 'index': 1130})
    sheet['values'].append({'symbol': 'RapidsAscentHeartGet', 'index': 1131})
    sheet['values'].append({'symbol': 'KanaletMoatHeartGet', 'index': 1132})
    sheet['values'].append({'symbol': 'SouthBayHeartGet', 'index': 1133})
    sheet['values'].append({'symbol': 'TaltalCrossingHeartGet', 'index': 1134})
    sheet['values'].append({'symbol': 'TaltalEastHeartGet', 'index': 1135})
    sheet['values'].append({'symbol': 'TaltalWestHeartGet', 'index': 1136})
    sheet['values'].append({'symbol': 'TurtleRockHeartGet', 'index': 1137})
    sheet['values'].append({'symbol': 'PotholeHeartGet', 'index': 1138})
    sheet['values'].append({'symbol': 'WoodsCrossingHeartGet', 'index': 1139})
    sheet['values'].append({'symbol': 'WoodsNorthCaveHeartGet', 'index': 1140})
    sheet['values'].append({'symbol': 'DiamondIslandHeartGet', 'index': 1141})

    sheet['values'].append({'symbol': 'TailCaveInstrumentGet', 'index': 1142})
    sheet['values'].append({'symbol': 'BottleGrottoInstrumentGet', 'index': 1143})
    sheet['values'].append({'symbol': 'KeyCavernInstrumentGet', 'index': 1144})
    sheet['values'].append({'symbol': 'AnglersTunnelInstrumentGet', 'index': 1145})
    sheet['values'].append({'symbol': 'CatfishsMawInstrumentGet', 'index': 1146})
    sheet['values'].append({'symbol': 'FaceShrineInstrumentGet', 'index': 1147})
    sheet['values'].append({'symbol': 'EaglesTowerInstrumentGet', 'index': 1148})
    sheet['values'].append({'symbol': 'TurtleRockInstrumentGet', 'index': 1149})
    
    sheet['values'].append({'symbol': 'TradeYoshiDollGet', 'index': 1150})
    sheet['values'].append({'symbol': 'TradeRibbonGet', 'index': 1151})
    sheet['values'].append({'symbol': 'TradeDogFoodGet', 'index': 1152})
    sheet['values'].append({'symbol': 'TradeBananasGet', 'index': 1153})
    sheet['values'].append({'symbol': 'TradeStickGet', 'index': 1154})
    sheet['values'].append({'symbol': 'TradeHoneycombGet', 'index': 1155})
    sheet['values'].append({'symbol': 'TradePineappleGet', 'index': 1156})
    sheet['values'].append({'symbol': 'TradeHibiscusGet', 'index': 1157})
    sheet['values'].append({'symbol': 'TradeLetterGet', 'index': 1158})
    sheet['values'].append({'symbol': 'TradeBroomGet', 'index': 1159})
    sheet['values'].append({'symbol': 'TradeFishingHookGet', 'index': 1160})
    sheet['values'].append({'symbol': 'TradeNecklaceGet', 'index': 1161})
    sheet['values'].append({'symbol': 'TradeMermaidsScaleGet', 'index': 1162})
    sheet['values'].append({'symbol': 'MermaidCaveItemGet', 'index': 1163})

    sheet['values'].append({'symbol': 'KikiGone', 'index': 1164})

    sheet['values'].append({'symbol': 'BombsFound', 'index': 1165})
    sheet['values'].append({'symbol': 'BombBagFound', 'index': 1166})

    sheet['values'].append({'symbol': 'MushroomFound', 'index': 1167})
    sheet['values'].append({'symbol': 'PowderBagFound', 'index': 1168})

    sheet['values'].append({'symbol': 'PotholeGet', 'index': 1169})

    sheet['values'].append({'symbol': 'PrizeGet1', 'index': 1170})
    sheet['values'].append({'symbol': 'PrizeGet2', 'index': 1171})
    sheet['values'].append({'symbol': 'PrizeGet3', 'index': 1172})
    sheet['values'].append({'symbol': 'PrizeGet4', 'index': 1173})
    sheet['values'].append({'symbol': 'PrizeGet5', 'index': 1174})
    sheet['values'].append({'symbol': 'PrizeGet6', 'index': 1175})

    sheet['values'].append({'symbol': 'Bottle2Get', 'index': 1176})
    sheet['values'].append({'symbol': 'FishingBottleGet', 'index': 1177})

    sheet['values'].append({'symbol': 'owl-statue-below-D8', 'index': 1178})
    sheet['values'].append({'symbol': 'owl-statue-pothole', 'index': 1179})
    sheet['values'].append({'symbol': 'owl-statue-above-cave', 'index': 1180})
    sheet['values'].append({'symbol': 'owl-statue-moblin-cave', 'index': 1181})
    sheet['values'].append({'symbol': 'owl-statue-south-bay', 'index': 1182})
    sheet['values'].append({'symbol': 'owl-statue-desert', 'index': 1183})
    sheet['values'].append({'symbol': 'owl-statue-maze', 'index': 1184})
    sheet['values'].append({'symbol': 'owl-statue-taltal-east', 'index': 1185})
    sheet['values'].append({'symbol': 'owl-statue-rapids', 'index': 1186})

    sheet['values'].append({'symbol': 'D1-owl-statue-spinies', 'index': 1187})
    sheet['values'].append({'symbol': 'D1-owl-statue-3-of-a-kind', 'index': 1188})
    sheet['values'].append({'symbol': 'D1-owl-statue-long-hallway', 'index': 1189})

    sheet['values'].append({'symbol': 'D2-owl-statue-first', 'index': 1190})
    sheet['values'].append({'symbol': 'D2-owl-statue-second', 'index': 1191})
    sheet['values'].append({'symbol': 'D2-owl-statue-third', 'index': 1192})

    sheet['values'].append({'symbol': 'D3-owl-statue-basement-north', 'index': 1193})
    sheet['values'].append({'symbol': 'D3-owl-statue-arrow', 'index': 1194})
    sheet['values'].append({'symbol': 'D3-owl-statue-northwest', 'index': 1195})

    sheet['values'].append({'symbol': 'D4-owl-statue', 'index': 1196})

    sheet['values'].append({'symbol': 'D5-owl-statue-south', 'index': 1197})
    sheet['values'].append({'symbol': 'D5-owl-statue-north', 'index': 1198})
    
    sheet['values'].append({'symbol': 'D6-owl-statue-ledge', 'index': 1199})
    sheet['values'].append({'symbol': 'D6-owl-statue-southeast', 'index': 1200})
    sheet['values'].append({'symbol': 'D6-owl-statue-canal', 'index': 1201})

    sheet['values'].append({'symbol': 'D7-owl-statue-ball', 'index': 1202})
    sheet['values'].append({'symbol': 'D7-owl-statue-kirbys', 'index': 1203})
    sheet['values'].append({'symbol': 'D7-owl-statue-4th-pillar', 'index': 1204})

    sheet['values'].append({'symbol': 'D8-owl-statue-above-smasher', 'index': 1205})
    sheet['values'].append({'symbol': 'D8-owl-statue-below-gibdos', 'index': 1206})
    sheet['values'].append({'symbol': 'D8-owl-statue-eye-statue', 'index': 1207})

    sheet['values'].append({'symbol': 'D0-owl-statue-left', 'index': 1208})
    sheet['values'].append({'symbol': 'D0-owl-statue-center', 'index': 1209})
    sheet['values'].append({'symbol': 'D0-owl-statue-right', 'index': 1210})

    sheet['values'].append({'symbol': 'RoosterFound', 'index': 1211})
    sheet['values'].append({'symbol': 'BowWowFound', 'index': 1212})

    sheet['values'].append({'symbol': 'DampeSword', 'index': 1213})
    sheet['values'].append({'symbol': 'DampeShield', 'index': 1214})
    sheet['values'].append({'symbol': 'DampeBracelet', 'index': 1215})
    sheet['values'].append({'symbol': 'DampeLens', 'index': 1216})

    sheet['values'].append({'symbol': 'PotholeKeySpawn', 'index': 1217})

    sheet['values'].append({'symbol': 'KeyGetField06I', 'index': 1218})
    sheet['values'].append({'symbol': 'KeyGetField06K', 'index': 1219})
    sheet['values'].append({'symbol': 'KeyGetKanalet02A', 'index': 1220})
    sheet['values'].append({'symbol': 'KeyGetKanalet01C', 'index': 1221})
    sheet['values'].append({'symbol': 'KeyGetKanalet01D', 'index': 1222})
    
    # sheet['values'].append({'symbol': 'ShopShovelGet', 'index': 1223})
    # sheet['values'].append({'symbol': 'ShopBowGet', 'index': 1224})
    # sheet['values'].append({'symbol': 'ShopHeartGet', 'index': 1225})
    # sheet['values'].append({'symbol': 'ShopShovelGet', 'index': 1200})
    # sheet['values'].append({'symbol': 'ShopShovelGet', 'index': 1200})
    # sheet['values'].append({'symbol': 'ShopShovelGet', 'index': 1200})
